apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      serviceAccountName: olas-reader
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api
        image: ghcr.io/jaime-carbo/olas:8bb1fc551f94cef83520bf8234aaf329d98bbc08
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGODB_URI
          value: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-service:27017
        - name: MONGODB_DB
          value: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api-svc
spec:
  type: ClusterIP
  selector:
    app: demo-api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-production
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jaime-carbo.duckdns.org
    secretName: demo-tls
  rules:
  - host: jaime-carbo.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-api-svc
            port:
              number: 80
